---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options: ./data:Z
  labels:
    app: zabbix
  name: zabbix
spec:
  containers:
    - args:
        - --character-set-server=utf8
        - --collation-server=utf8_bin
        - --default-authentication-plugin=mysql_native_password
      env:
        - name: TERM
          value: xterm
        - name: MYSQL_DATABASE
          value: zabbix
        - name: MYSQL_PASSWORD
          value: zabbix_pwd
        - name: MYSQL_ROOT_PASSWORD
          value: root_pwd
        - name: MYSQL_USER
          value: zabbix
      image: docker.io/library/mysql:8.0
      name: zb-data
      ports:
        - containerPort: 8080
          hostPort: 8080
        - containerPort: 8443
          hostPort: 8443
        - containerPort: 10051
          hostPort: 10051
      tty: true
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: database
    - args:
        - /usr/sbin/zabbix_java_gateway
      image: docker.io/zabbix/zabbix-java-gateway:latest
      name: zb-gateway
      securityContext:
        runAsNonRoot: true
      tty: true
    - args:
        - /usr/sbin/zabbix_server
        - --foreground
        - -c
        - /etc/zabbix/zabbix_server.conf
      env:
        - name: DB_SERVER_HOST
          value: zb-data
        - name: MYSQL_ROOT_PASSWORD
          value: root_pwd
        - name: ZBX_JAVAGATEWAY
          value: zb-gateway
        - name: MYSQL_DATABASE
          value: zabbix
        - name: MYSQL_USER
          value: zabbix
        - name: MYSQL_PASSWORD
          value: zabbix_pwd
      image: docker.io/zabbix/zabbix-server-mysql:latest
      name: zb-server
      securityContext:
        runAsNonRoot: true
      tty: true
      volumeMounts:
        - mountPath: /var/lib/zabbix/export
          name: export-pvc
        - mountPath: /var/lib/zabbix/snmptraps
          name: snnmp-pvc
    - args:
        - /usr/sbin/zabbix_agentd
        - --foreground
        - -c
        - /etc/zabbix/zabbix_agentd.conf
      env:
        - name: ZBX_SERVER_HOST
          value: zb-server
      image: docker.io/zabbix/zabbix-agent:latest
      name: zb-agent
      securityContext:
        runAsNonRoot: true
    - env:
        - name: PHP_TZ
          value: Asia/Jakarta
        - name: DB_SERVER_HOST
          value: zb-data
        - name: MYSQL_PASSWORD
          value: zabbix_pwd
        - name: MYSQL_ROOT_PASSWORD
          value: root_pwd
        - name: ZBX_SERVER_HOST
          value: zb-server
        - name: MYSQL_USER
          value: zabbix
        - name: MYSQL_DATABASE
          value: zabbix
      image: docker.io/zabbix/zabbix-web-nginx-mysql:latest
      name: zb-web
      securityContext:
        runAsNonRoot: true
      tty: true
  volumes:
    - hostPath:
        path: ./data
        type: Directory
      name: database
    - name: export-pvc
      persistentVolumeClaim:
        claimName: export
    - name: snnmp-pvc
      persistentVolumeClaim:
        claimName: snmp
